# src/content/site.yaml
# Editado por Decap CMS

hero_video: /videos/hero.mp4
hero_title_es: "FLORES PARA LOS QUE SIEMPRE ESTÁN"
hero_title_en: "FLOWERS FOR THOSE WHO ARE ALWAYS WITH YOU"
hero_subtitle_es: "Porque cuidar no depende de dónde estés. Con tu decisión, nosotros llegamos por ti."
hero_subtitle_en: "Because caring doesn't depend on where you are. With your decision, we go for you."
